version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: newcrm:prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  seed:
    image: newcrm:prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["tsx", "src/db/seed.ts"]
    networks:
      - app-network
    restart: on-failure:3

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: